bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: FeRDTphRb4sHpyk46DG/OCx2GlW89Y730zAEZ/f7z7pQVYhXNOf4BW3ezE/9I+kK/isQxwIvrm73H+Y+gtpJzXA6isBpnHSVckpFjbFNoY7wS5kQF6dCniJPOl/GwSmaF1JQ7tu3KqPD8jM7xgQSvvL8/pNeiNMw8VEbwb/1twINoSDnN2Vp/fkL4+8YRxrERWsvahTq4+DoXu2meJV1kOgbvhDK19RwCqw6f4nng8Dsf8/S9B6DyehdnoCBO+fnF2UcSV327frF3qxQLKTaaHK/65AqCBxg0edEAwn3jc1BqxylPUnspf7gWjfWSm5vMBVo49WW7qHfMqyf2JHr5OAle5VVqPNCmDFAUDccuS70Kyjo1fmptYFjEPYXJw4erdrGdtK9JIBVkTW42JtHmGWPnJRctEJotvGgwazdo/NWLER0D9SMphKV3ymaYVrzbjmpF/9DybnT/HeR+VccdZTHOvlubO2rMOrStCq3Mhxkk+b2B2lcuO0hyQX5tVW1eZTWQ/7/AXN9nBLu1Vy5YOvwZaDqXuwKudxQMR2iQOV0bRpEq5pDy1jHzP5HWDPZg94KZIEyMqmw94+4LhS8UxaLYpANvnAi8xC4rNq+LtUKEhz4uKQQCSfODnxCvPnbXb5RnFDOjSZ4NdH8/SOHmCuokX49pq/ASdbbSzMUju8=
conda_forge_output_validation: false
